// Pick the stylesheet for the surface this build is for.
//
// WHY A BUILD STEP AND NOT A CONDITIONAL IMPORT
// The two surfaces run different Tailwind v4 design systems, and both declare
// `@theme` tokens with different shapes -- the consumer apps use brand/ink
// tokens, the admin console maps the same ProHealth palette onto shadcn names
// (`--primary`, `--muted-foreground`, …). Importing both would let one
// silently win for every `bg-primary` on the other surface. CSS cannot branch
// at runtime, so the choice is made here, before the bundler ever sees it.
//
// This is why the frontend is built once PER SURFACE rather than once in total:
// the JavaScript could have branched on SURFACE; the stylesheet cannot.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const surface = process.env.TELEMED_SURFACE ?? process.env.NEXT_PUBLIC_TELEMED_SURFACE ?? "patient";
const sheet = surface === "admin" ? "admin.css" : "consumer.css";

const banner = `/* GENERATED by scripts/select-surface.mjs for TELEMED_SURFACE=${surface}. Do not edit. */\n`;
const body = readFileSync(join(root, "styles", sheet), "utf8");
const dst = join(root, "app", "globals.css");

mkdirSync(dirname(dst), { recursive: true });
let current = null;
try {
  current = readFileSync(dst, "utf8");
} catch {
  /* first run */
}
if (current !== banner + body) {
  writeFileSync(dst, banner + body);
}
console.log(`surface=${surface} -> app/globals.css (${sheet})`);
